# Generated by Django 5.0.6 on 2024-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('works', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
    ]
